// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://amiaefqxmjnephupimto.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFtaWFlZnF4bWpuZXBodXBpbXRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzY2MDUyMTAsImV4cCI6MjA1MjE4MTIxMH0.QnFcj0zUoUKlcVVQ8zWqA18iC7J_XU_L4Bm5wX95Koc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);